export default {
  colorPrimary: '#2c2c38',
  colorPrimaryLight: '#41414b',
  colorOnPrimary: '#FFFFFF',
  buttonSuccessful: '#00ff00',
  buttonUnsuccessful: '#ff0000',
  buttonWithdrawn: '#41414b',
  tabIconDefault: '#bebebe',
  tabIconSelected: '#ffffff',
  tabBar: '#fefefe',
  errorBackground: 'red',
  errorText: '#fff',
  warningBackground: '#EAEB5E',
  warningText: '#666804',
  noticeBackground: '#ffffff',
  noticeText: '#fff',
  applicationStageSuccessful: '#00cc00',
  applicationStageUnsuccessful: '#cc0000',
  applicationStageWithdrawn: '#41414b',
};
