# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'JobCatcherReactNative' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JobCatcherReactNative

    pod 'Firebase/Core', '~> 5.15.0'
    pod 'Firebase/Auth', '~> 5.15.0'
    pod 'Firebase/Firestore', '~> 5.15.0'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNGoogleSignin', :path => '../node_modules/react-native-google-signin'

  target 'JobCatcherReactNativeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'JobCatcherReactNative-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JobCatcherReactNative-tvOS

  target 'JobCatcherReactNative-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
